name: Pulumi Preview PR Label Action
description: Decorate your PR with context from Pulumi Preview output.
author: "@urcomputeringpal"
inputs:
  github-token: 
    description: Token to use
    default: ${{ github.token }}
  pulumi-output: 
    description: Pulumi output to parse
    required: true
  label-prefix:
    description: String to prefix your label with
    default: Pulumi

runs:
  using: 'node16'
  main: 'dist/index.js'
